### ISSUE TITLE
Cannot logon to remote host using SSH Certificate

### ISSUE THREAD

**Issue by AndrewCopeland** [infamousjoeg/cyberark-aam-pkiaas#128]
**Describe the bug**
Cannot logon to remote host using SSH Certificate
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by rcobbins** [comment]
Updated codebase to return SSH CA certificate for use by sshd.  Resolves this issue.
