### ISSUE TITLE
Move InitConfig() to endpoint to allow customization of addt'l service names to avoid conflict

### ISSUE THREAD

**Issue by infamousjoeg** [infamousjoeg/cyberark-aam-pkiaas#97]
**Is your feature request related to a problem? Please describe.**
Currently, the initial policy is loaded from within the API package.  This loads on init every time and is static.  This would cause a 2nd service to assume the same identity as the 1st.  By making this a configurable endpoint, we can begin to scale additional services without conflict.

**Describe the solution you'd like**
I don't know -- ask @AndrewCopeland.

**Comment by AndrewCopeland** [comment]
We have moved this to the `pkiaas init` command
